$color = rgba(40, 40, 40, 1)
$inner_color = rgba(40, 40, 40, 0.66)
$outer_color = rgba(204, 120, 51, 1)
$font_color = rgba(230, 225, 220, 1)
$placeholder_color = rgba(230, 225, 220, 0.7)
$check_color = rgba(137, 175, 144, 1)
